In [1]:
import os
import pandas as pd

In [9]:
# csv 폴더에 있는 2018 폴더의 csv 파일들을 모두 결합하여 하나의 데이터 프레임으로 생성

# 파일의 경로를 변수에 대입
file_path = "../csv/2018/"

# 경로의 파일 리스트를 생성
file_list = os.listdir(file_path)
file_list

# 비어있는 데이터프레임 생성 - 내가 원하는 결합을 시키기 위해서 비어있는 데이터프레임을 만들고 시작
result = pd.DataFrame()

# 파일 리스트를 반복문을 이용하여 반복
for file in file_list :

    # 파일의 경로와 파일 리스트의 각원소의 값들을 결합하여 read_csv()로 데이터프레임 생성
    df = pd.read_csv(file_path + file)

    # concat()를 이용하여 비어있는 데이터 프레임과 결합
    result = pd.concat([result, df], axis=0, ignore_index=True)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 0: unexpected end of data

In [8]:
result.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42365 entries, 0 to 42364
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                42365 non-null  int64
 1   title              42365 non-null  object
 2   url                42365 non-null  object
 3   dept_nm_lvl_1      42365 non-null  object
 4   dept_nm_lvl_2      42297 non-null  object
 5   dept_nm_lvl_3      36782 non-null  object
 6   dept_nm_lvl_4      11473 non-null  object
 7   dept_nm_lvl_5      1983 non-null   object
 8   exec_yr            42365 non-null  int64
 9   exec_month         42365 non-null  int64
 10  expense_budget     1648 non-null   float64
 11  expense_execution  1307 non-null   float64
 12  category           1020 non-null   object
 13  dept_nm_full       42365 non-null  object
 14  exec_dt            42365 non-null  object
 15  exec_loc           41891 non-null  object
 16  exec_purpose       42365 non-null  object
 17  target_nm          42254 non-null  object
 18  payment_method     42365 non-null  object
 19  exec_amount        42365 non-null  int64
dtypes: float64(2), int64(4), object(14)
memory usage: 6.5+ MB

In [36]:
# 특정 경로에 있는 파일 목록을 하나의 데이터프레임으로 결합하는 함수 생성
def list_load(_path, _end) :
        # _path : 파일의 경로
        # _end : 파일의 확장자

        # _path의 마지막 문자열이 '/' 가 아니라면?
        # if not(_path.endswith('/')):
        if _path[-1] !='/':
               _path = _path + '/' #<- 이것만 써도 되긴 함.
       
        # 특정 경로의 파일 리스트 생성
        file_list = os.listdir(_path)

        # 특정 확장자로 이루어진 파일 리스트를 생성
        file_list2 =[]

        for file in file_list :
               if file.endswith(_end):
                      file_list2.append(file)

        # 비어있는 데이터 프레임 생성
        result = pd.DataFrame()

        # 반복문 생성
        for file in file_list2 :
                # _end가 'csv'인 경우
                if _end == 'csv':
                    df = pd.read_csv(_path+file)
                elif _end == 'json' :
                       df = pd.read_json(_path+file)
                #elif (_end =='xls') | (_end == 'xlsx'): 이걸
                elif _end in ['xls', 'xlsx'] : # 이렇게 표현해도 된다. 더 간단하게.
                       df = pd.read_excel(_path+file)
                else:
                       return "지원하지 않는 확장자입니다."
                
                # 유니언 결합
                result = pd.concat([result, df], axis=0, ignore_index=True)

        return result

In [16]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.2-py2.py3-none-any.whl (249 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 250.0/250.0 kB 5.8 MB/s eta 0:00:0000:01
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.1.2
Note: you may need to restart the kernel to use updated packages.

In [37]:
list_load('../csv/2021', 'xlsx').info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83819 entries, 0 to 83818
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                83819 non-null  int64
 1   title              83819 non-null  object
 2   url                83819 non-null  object
 3   dept_nm_lvl_1      83819 non-null  object
 4   dept_nm_lvl_2      83819 non-null  object
 5   dept_nm_lvl_3      67930 non-null  object
 6   dept_nm_lvl_4      24831 non-null  object
 7   dept_nm_lvl_5      1473 non-null   object
 8   exec_yr            83819 non-null  int64
 9   exec_month         83819 non-null  int64
 10  expense_budget     60524 non-null  float64
 11  expense_execution  60524 non-null  float64
 12  category           980 non-null    object
 13  dept_nm_full       83819 non-null  object
 14  exec_dt            83819 non-null  object
 15  exec_loc           83185 non-null  object
 16  exec_purpose       83819 non-null  object
 17  target_nm          83467 non-null  object
 18  payment_method     83819 non-null  object
 19  exec_amount        83819 non-null  int64
 20  bimok              18427 non-null  object
dtypes: float64(2), int64(4), object(15)
memory usage: 13.4+ MB

In [23]:
file_list = os.listdir('../csv/2021/')
file_list

['202110_expense_list.xlsx',
 '202110_expense_list.xml',
 '202105_expense_list.json',
 '202104_expense_list.xml',
 '202109_expense_list.xlsx',
 '202107_expense_list.csv',
 '202111_expense_list.xlsx',
 '202103_expense_list.csv',
 '202104_expense_list.json',
 '202108_expense_list.csv',
 '202108_expense_list.xlsx',
 '202101_expense_list.json',
 '202112_expense_list.xlsx',
 '202111_expense_list.xml',
 '202112_expense_list.csv',
 '202107_expense_list.json',
 '202106_expense_list.csv',
 '202105_expense_list.xml',
 '202102_expense_list.json',
 '202101_expense_list.xml',
 '202102_expense_list.csv',
 '202106_expense_list.json',
 '202103_expense_list.json',
 '202109_expense_list.csv',
 '202105_expense_list.csv',
 '202103_expense_list.xlsx',
 '202106_expense_list.xml',
 '202112_expense_list.xml',
 '202111_expense_list.csv',
 '202106_expense_list.xlsx',
 '202109_expense_list.xml',
 '202102_expense_list.xlsx',
 '202102_expense_list.xml',
 '202112_expense_list.json',
 '202101_expense_list.csv',
 '202107_expense_list.xlsx',
 '202107_expense_list.xml',
 '202108_expense_list.json',
 '202101_expense_list.xlsx',
 '202104_expense_list.csv',
 '202111_expense_list.json',
 '202110_expense_list.csv',
 '202104_expense_list.xlsx',
 '202109_expense_list.json',
 '202108_expense_list.xml',
 '202110_expense_list.json',
 '202105_expense_list.xlsx',
 '202103_expense_list.xml']

In [26]:
file_list2 = []

for file in file_list :
    # if 조건식(특정한 확장자를 만들 경우)
    if file.endswith('.csv'):
        file_list2.append(file)

    # 문자열에 특정한 문자가 포함되어있는가?
    # if 'csv' in file :

file_list2

['202107_expense_list.csv',
 '202103_expense_list.csv',
 '202108_expense_list.csv',
 '202112_expense_list.csv',
 '202106_expense_list.csv',
 '202102_expense_list.csv',
 '202109_expense_list.csv',
 '202105_expense_list.csv',
 '202111_expense_list.csv',
 '202101_expense_list.csv',
 '202104_expense_list.csv',
 '202110_expense_list.csv']

In [43]:
import reference.list_load as ll
import imp # 저장 전 import를 한다면 다시 불러오지 않음. 리로드 해줘야함.

/var/folders/9c/kgyp1x493jz2jb29m1zs2bb40000gn/T/ipykernel_4563/2026946884.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import imp

In [45]:
imp.reload(ll) # 리로드

In [46]:
ll.list_load('../csv/2022/', 'csv')

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,25741578,2022년 3월 사업소 상수도사업본부 본부 경영관리부 업무추진비 - 기관운영 시책추...,http://opengov.seoul.go.kr/expense/25741578,사업소,상수도사업본부,본부,경영관리부,NaN,2022,3,0,0,NaN,상수도사업본부 경영관리부 총무과,2022-03-31 00:00,동국대학교 병원,소속 상근 직원(강동수소사업소 김00 빙부상)의 경조사비(부의) 지급,부본부장,현금,50000
1,25741578,2022년 3월 사업소 상수도사업본부 본부 경영관리부 업무추진비 - 기관운영 시책추...,http://opengov.seoul.go.kr/expense/25741578,사업소,상수도사업본부,본부,경영관리부,NaN,2022,3,0,0,NaN,상수도사업본부 경영관리부 총무과,2022-03-31 00:00,우리병원 장례식장,소속 상근 직원(강동수소사업소 김00 빙부상)의 경조사비(부의) 지급,본부장,현금,50000
2,25741578,2022년 3월 사업소 상수도사업본부 본부 경영관리부 업무추진비 - 기관운영 시책추...,http://opengov.seoul.go.kr/expense/25741578,사업소,상수도사업본부,본부,경영관리부,NaN,2022,3,0,0,NaN,상수도사업본부 경영관리부 총무과,2022-03-10 12:50,햇빛촌 마트(중구 중림로 10),직접고용근로자 등 휴게실 커피 등 소모품 구매,총무과 공무직 등 전직원,카드,160000
3,25741578,2022년 3월 사업소 상수도사업본부 본부 경영관리부 업무추진비 - 기관운영 시책추...,http://opengov.seoul.go.kr/expense/25741578,사업소,상수도사업본부,본부,경영관리부,NaN,2022,3,0,0,NaN,상수도사업본부 경영관리부 총무과,2022-03-30 15:10,예성청과(송파구 양재대로 932 가락시장),산하기관 협장방문용 직원 격려,"수도사업소(동부, 강서, 남부) 및 정수센터(강북, 영등포) 전직원",카드,485000
4,25741578,2022년 3월 사업소 상수도사업본부 본부 경영관리부 업무추진비 - 기관운영 시책추...,http://opengov.seoul.go.kr/expense/25741578,사업소,상수도사업본부,본부,경영관리부,NaN,2022,3,0,0,NaN,상수도사업본부 경영관리부 홍보민원과,2022-03-02 13:49,홍루이젠(서울 종로구 송월길99),홍보민원과 부서운영업무추진비(직원격려 간식 구매),홍보민원과 전직원,카드,36100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19349,25870795,2022년 4월 사업소 서울도서관 정보서비스과 업무추진비 - 부서운영,http://opengov.seoul.go.kr/expense/25870795,사업소,서울도서관,정보서비스과,NaN,NaN,2022,4,0,0,NaN,서울도서관 정보서비스과,2022-04-27 12:50,The Place 광화문SFC점,현업부서 직원 격려 식사비 지급,이서하 외 4명,카드,96600
19350,25870795,2022년 4월 사업소 서울도서관 정보서비스과 업무추진비 - 부서운영,http://opengov.seoul.go.kr/expense/25870795,사업소,서울도서관,정보서비스과,NaN,NaN,2022,4,0,0,NaN,서울도서관 정보서비스과,2022-04-25 12:29,왕비집 시청무교점,현업부서 직원 격려 식사비 지급,정보서비스과장 외 8명,카드,160000
19351,25870795,2022년 4월 사업소 서울도서관 정보서비스과 업무추진비 - 부서운영,http://opengov.seoul.go.kr/expense/25870795,사업소,서울도서관,정보서비스과,NaN,NaN,2022,4,0,0,NaN,서울도서관 정보서비스과,2022-04-21 16:27,서울시청 본관매점,부서운영을 위한 다과 구입,정보서비스과 직원 25명,제로페이,200000
19352,25870795,2022년 4월 사업소 서울도서관 정보서비스과 업무추진비 - 부서운영,http://opengov.seoul.go.kr/expense/25870795,사업소,서울도서관,정보서비스과,NaN,NaN,2022,4,0,0,NaN,서울도서관 정보서비스과,2022-04-21 15:51,㈜파피루스,부서운영을 위한 음료 구입,정보서비스과 직원 25명,카드,28000
19353,25870795,2022년 4월 사업소 서울도서관 정보서비스과 업무추진비 - 부서운영,http://opengov.seoul.go.kr/expense/25870795,사업소,서울도서관,정보서비스과,NaN,NaN,2022,4,0,0,NaN,서울도서관 정보서비스과,2022-04-20 16:44,㈜파피루스,부서운영을 위한 다과 구입,정보서비스과 직원 25명,카드,14000